version: '3.8'

services:
  api:
    build: .
      # dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:     
      - .:/app      
      - /app/node_modules

  db:
    image: postgres:17.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
